<a href="https://colab.research.google.com/github/esubalewmilam-hue/MIS433/blob/main/week2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Assignment: Python Basics
We assume you are using Python 3 in this course.

## Question 1

You've learned different data types in Python. Now, let's test your knowledge.

You need to use to format strings.

Write a program using the "f-strings" (https://realpython.com/python-f-strings/) and user input function to convert temperatures from Fahrenheit to Celsius. [Formula: Celsius = (Fahrenheit – 32)*5/9]

Hint: you may need int() or float() function

An example program output:
```
Please enter the temperature in Fahrenheit: 140
140F is 60.0 in Celsius.
```

In [1]:
# an example of f-strings and user input function
username = input('What\'s your name? ')
print(f'Welcome, {username}!')

What's your name? esu
Welcome, esu!


In [2]:
# complete your program here
f = float(input('Please enter the temperature in Fahrenheit: '))

print(f)

#Celsius = (Fahrenheit – 32)*5/9
c = (f - 32) * 5/9
print(str(f) + ' F is ' + str(c) + ' in Celsius.')
#print(str(f)+'F is '+str(c)+' in Celsius. ')

Please enter the temperature in Fahrenheit: 70
70.0
70.0 F is 21.11111111111111 in Celsius.


Now, do the oppsoite by convert temperatures from Celsius to Fahrenheit.
Another example:
```
Please enter the temperature in Celcius: 60
60C is 140.0 in Fahrenheit.
```

In [5]:
# complete your program here
# complete your program here
c = float(input('Please enter the temperature in Celsius: '))
f = c * 9/5 + 32
print(str(c) + ' C is ' + str(f) + ' in Fahrenheit.')

Please enter the temperature in Celsius: 34
34.0 C is 93.2 in Fahrenheit.


Next, let's make it a bit challenging by adding conditional statements to convert temperatures to and from Celsius, Fahrenheit. [Formula: Celsius/5 = (Fahrenheit – 32)/9]

An example program output:
```
Please enter the temperature: 60
Is this in Celsius or Fahrenheit? C
60C is 140 in Fahrenheit
```

Another example:
```
Please enter the temperature: 140
Is this Celsius or Fahrenheit? F
140F is 60 in Celsius
```

In [8]:
d = float(input('Please enter the temperature: '))
m = input('Is this in Celsius or Fahrenheit? ')

if m == 'C':
    f = d * 9/5 + 32
    print(str(d) + 'C is ' + str(f) + ' in Fahrenheit')
elif m == 'F':
    c = (d - 32) * 5/9
    print(str(d) + 'F is ' + str(c) + ' in Celsius')
else:
    print('Please enter C or F.')


Please enter the temperature: 88
Is this in Celsius or Fahrenheit? C
88.0C is 190.4 in Fahrenheit


## Question 2

Have some fun with strings.

In [9]:
sentence = "Talk is cheap. Show me the code - Linus Torvalds"

In [10]:
# Find the length of this sentence
print(len(sentence))


48


In [11]:
# Convert the whole string to lower case.
print(sentence.lower())

talk is cheap. show me the code - linus torvalds


In [12]:
# Extract a substring from the 10th character from left to the 10th character from right.
print(sentence[9:-9])

heap. Show me the code - Linus


In [13]:
# Split the sentence into a list of substrings by space ' '.
print(sentence.split(' '))

['Talk', 'is', 'cheap.', 'Show', 'me', 'the', 'code', '-', 'Linus', 'Torvalds']


In [14]:
# Given the sentence, output a list of words in lowercase (without symbols such as '.' and '-').
words = sentence.lower().replace('.', '').replace('-', '').split()
words

['talk', 'is', 'cheap', 'show', 'me', 'the', 'code', 'linus', 'torvalds']


In [17]:
# Count the total number of vowels in the sentence.
vowels = ['a','e','i','o','u']
#vowels = 'aeiou'
for v in vowels:
    vowel_count += sentence.lower().count(v)
#idk
vowel_count

NameError: name 'vowel_count' is not defined

In [18]:
# Find the positions (indexes) of all vowels in the sentence.
vowels = ['a', 'e', 'i', 'o', 'u']
vowel_positions = []
for i in range(len(sentence)):
  if sentence[i].lower() in vowels:
        vowel_positions.append(i)

vowel_positions

[1, 5, 10, 11, 17, 21, 25, 28, 30, 35, 37, 41, 44]


## Question 3

Review list comprehension if needed: https://realpython.com/list-comprehension-python/

The formula for list comprehension is: `new_list = [expression for member in iterable (if conditional)]`

You need to do the following:

In [19]:
# Use a loop to create a list of 5 cube numbers and print the list：[0, 1, 8, 27, 64]
cubes = []
for i in range(5):
    cubes.append(i ** 3)

cubes

[0, 1, 8, 27, 64]


In [20]:
# Use list comprehension to create the same list
cubes = [i ** 3 for i in range(5)]
cubes

[0, 1, 8, 27, 64]


In [21]:
# Find the postions (indexes) of all vowels in a sentence using list comprehension
sentence = "Toto, I\'ve a feeling we\'re not in Kansas anymore. - THE WIZARD OF OZ (1939)"
vowel_positions = [
    i for i in range(len(sentence))
    if sentence[i].lower() in 'aeiou'
]

vowel_positions

[1, 3, 6, 9, 11, 14, 15, 17, 22, 25, 28, 31, 35, 38, 41, 45, 47, 54, 57, 59, 63, 66]


In [26]:
# Use a loop to create a list of first n numbers in the Fibonacci sequence
# [0, 1, 1, 2, 3, 5, 8, ...]
fibonacci = []
n = int(input('How many numbers do you want? '))

# add your code here
a = 0
b = 1

for i in range(n):
    fibonacci.append(a)
    a, b = b, a + b

fibonacci

How many numbers do you want? 77
[0, 1, 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, 144, 233, 377, 610, 987, 1597, 2584, 4181, 6765, 10946, 17711, 28657, 46368, 75025, 121393, 196418, 317811, 514229, 832040, 1346269, 2178309, 3524578, 5702887, 9227465, 14930352, 24157817, 39088169, 63245986, 102334155, 165580141, 267914296, 433494437, 701408733, 1134903170, 1836311903, 2971215073, 4807526976, 7778742049, 12586269025, 20365011074, 32951280099, 53316291173, 86267571272, 139583862445, 225851433717, 365435296162, 591286729879, 956722026041, 1548008755920, 2504730781961, 4052739537881, 6557470319842, 10610209857723, 17167680177565, 27777890035288, 44945570212853, 72723460248141, 117669030460994, 190392490709135, 308061521170129, 498454011879264, 806515533049393, 1304969544928657, 2111485077978050, 3416454622906707]


## Question 4

This question is about Python dictionary.

|Vaccine|Efficacy|
|-----|-------|
|Pfizer|95%|
|Moderna|95%|
|AstraZeneca|72%|
|Johnson & Johnson|66%|

Source: https://www.biospace.com/article/comparing-covid-19-vaccines-pfizer-biontech-moderna-astrazeneca-oxford-j-and-j-russia-s-sputnik-v/

In [27]:
# Create a dictionary to save the data of vaccines and their efficacy. (save 95% as 0.95)
v_dict = {
'Pfizer': 0.95,
    'Moderna': 0.95,
    'AstraZeneca': 0.72,
    'Johnson & Johnson': 0.66
}

In [28]:
v = input('Which vaccine? ')
# print the efficacy of the vaccine
v = input('Which vaccine? ')

if v in v_dict:
    print(f'{v}: {v_dict[v]:.2%}')
else:
    print('Vaccine not found.')

Which vaccine? moderna
Which vaccine? Pfizer
Pfizer: 95.00%


In [29]:
# add another vaccine 'Sputnik V' with 91.4% efficacy rate to the dictionary
v_dict['Sputnik V'] = 0.914

In [30]:
# add another vaccine 'Sinovac' with 50.38% efficacy rate to the dictionary
v_dict['Sinovac'] = 0.5038

In [31]:
# Print vaccines with efficacy lower than 90%.
for vaccine, efficacy in v_dict.items():
    if efficacy < 0.90:
        print(f'{vaccine}: {efficacy:.2%}')

AstraZeneca: 72.00%
Johnson & Johnson: 66.00%
Sinovac: 50.38%


In [32]:
# delete the Sinovac vaccine from the dictionary.
del v_dict['Sinovac']

In [33]:
#Count the occurrence of each alphabet (no space ' ') in this sentence.
sentence = 'the quick brown fox jumps over the lazy dog'

# Save the result in a dictionary
ch_dict = {}
# Use a loop to iterate all characters
for ch in sentence:
    if ch != ' ':
        if ch in ch_dict:
            ch_dict[ch] += 1
        else:
            ch_dict[ch] = 1
# print the dictionary
ch_dict

{'t': 2, 'h': 2, 'e': 3, 'q': 1, 'u': 2, 'i': 1, 'c': 1, 'k': 1, 'b': 1, 'r': 2, 'o': 4, 'w': 1, 'n': 1, 'f': 1, 'x': 1, 'j': 1, 'm': 1, 'p': 1, 's': 1, 'v': 1, 'l': 1, 'a': 1, 'z': 1, 'y': 1, 'd': 1, 'g': 1}


## Quesion 5

Next, we will practice with Numpy arrays.  

In [34]:
import numpy as np

In [35]:
# create a 1-D array of first 20 positive even numbers (starting with 2)
np.array([])
even_numbers = np.arange(2, 41, 2)
even_numbers

[ 2  4  6  8 10 12 14 16 18 20 22 24 26 28 30 32 34 36 38 40]


In [36]:
# create a 1-D array of first 20 positive odd numbers (starting with 1)
np.array([])
odd_numbers = np.arange(1, 40, 2)
odd_numbers

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19, 21, 23, 25, 27, 29, 31, 33,
       35, 37, 39])

In [37]:
# create a 10x10 array in the following format:
# first row: [0,1,...,9]
# second row: [10,11,...,19]
# ...
# tenth row: [90,91,...,99]
np.array([])
numbers = np.arange(100).reshape(10, 10)
numbers

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [38]:
# Create a 10x10 array of normally distributed random values
# with mean 0 and standard deviation 1
M = np.random.normal(0, 1, size=(10, 10))
M.shape

(10, 10)

In [39]:
# Count the numbers in M with an absolute value greater than 1.
print(np.sum(np.abs(M) > 1))

29


In [53]:
# Reference: https://numpy.org/doc/stable/reference/random/generated/numpy.random.randint.html

# Input the number of rows (input an integer >= 3)
r = int(input('Row count: '))

# Input the number of rows (input another integer >= 3)
c = int(input('column count: '))


# Hint: you may want to use the function int().
while r < 3 or c < 3:
    print('Both dimensions must be at least 3.')
    r = int(input('Row count: '))
    c = int(input('Column count: '))
# Create a r x c array of random integers between 10 (inclusive) and 20 (exclusive).
arr = np.random.randint(10, 20, size=(r, c))
arr

Row count: 5
column count: 6


array([[13, 19, 14, 11, 13, 18],
       [13, 17, 13, 10, 10, 16],
       [16, 17, 11, 19, 10, 11],
       [12, 15, 17, 11, 10, 15],
       [16, 17, 14, 16, 18, 16]])

In [54]:
# output the element in the first row and the third column
arr[0, 2]

np.int64(14)

In [55]:
# output the element in the second row and the last column
arr[1, -1]

np.int64(16)

In [56]:
# output the second row of the array
arr[1, :]

array([13, 17, 13, 10, 10, 16])

In [57]:
# output the second last row of the array
arr[-2, :]

array([12, 15, 17, 11, 10, 15])

In [58]:
# output the second column of the array
arr[:, 1]

array([19, 17, 17, 15, 17])

In [59]:
# output the second last column of the array
arr[:, -2]

array([13, 10, 10, 10, 18])

In [60]:
# output the upper-left 3x3 sub-array
arr[:3, :3]

array([[13, 19, 14],
       [13, 17, 13],
       [16, 17, 11]])

In [61]:
# output the bottom-left 3x3 sub-array
arr[-3:, :3]

array([[16, 17, 11],
       [12, 15, 17],
       [16, 17, 14]])

In [62]:
# output the upper-right 3x3 sub-array
arr[:3, -3:]

array([[11, 13, 18],
       [10, 10, 16],
       [19, 10, 11]])

In [63]:
# output the bottom-right 3x3 sub-array
arr[-3:, -3:]

array([[19, 10, 11],
       [11, 10, 15],
       [16, 18, 16]])

In [ ]:
# Create a 1-D array from 1 to 50 (inclusive)
A = ...
# Reshape A to a 5x10 array in the following format:
# first row: [1,...,10]
# second row: [11,...,20]
# ...
# fifth row: [41,...,50]


In [ ]:
# add a row [51,...,60] to A


In [ ]:
# split the new A (6x10) to two 3x10 arrays A1 and A2


In [ ]:
# Add 10 to each element of A


In [ ]:
# Calculate the square root of each element in A


In [ ]:
# Above, we should have created a 10x10 array M of normally distributed random values
# with mean 0 and standard deviation 1
M.shape

In [ ]:
# Print the mean, standard devietion of all numbers in M


In [ ]:
# Print the maximumn, 3rd quartile, median, 1st quartile, and minimum in M
